weather_codes = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog and depositing rime fog",
    48: "Fog and depositing rime fog",
    51: "Drizzle: Light intensity",
    53: "Drizzle: Moderate intensity",
    55: "Drizzle: Dense intensity",
    56: "Freezing Drizzle: Light intensity",
    57: "Freezing Drizzle: Dense intensity",
    61: "Rain: Slight intensity",
    63: "Rain: Moderate intensity",
    65: "Rain: Heavy intensity",
    66: "Freezing Rain: Light intensity",
    67: "Freezing Rain: Heavy intensity",
    71: "Snow fall: Slight intensity",
    73: "Snow fall: Moderate intensity",
    75: "Snow fall: Heavy intensity",
    77: "Snow grains",
    80: "Rain showers: Slight intensity",
    81: "Rain showers: Moderate intensity",
    82: "Rain showers: Violent intensity",
    85: "Snow showers: Slight intensity",
    86: "Snow showers: Heavy intensity",
    95: "Thunderstorm: Slight or moderate",
    96: "Thunderstorm with slight hail",
    99: "Thunderstorm with heavy hail"
}

weather_codes_to_images = {
    0: "@/assets/images/sunny.jpg",
    1: "@/assets/images/partly-cloudy.png",
    2: "@/assets/images/cloudy-day.png",
    3: "@/assets/images/overcast.png",
    45: "@/assets/images/haze.png",
    48: "@/assets/images/haze.png",
    51: "@/assets/images/drizzle.png",
    53: "@/assets/images/drizzle.png",
    55: "@/assets/images/drizzle.png",
    56: "@/assets/images/drizzle.png",
    57: "@/assets/images/drizzle.png",
    61: "@/assets/images/light-rain.png",
    63: "@/assets/images/heavy-rain.png",
    65: "@/assets/images/heavy-rain.png",
    66: "@/assets/images/sleet.png",
    67: "@/assets/images/sleet.png",
    71: "@/assets/images/light-snow.png",
    73: "@/assets/images/moderate-snow.png",
    75: "@/assets/images/moderate-snow.png",
    77: "@/assets/images/moderate-snow.png",
    80: "@/assets/images/light-rain.png",
    81: "@/assets/images/heavy-rain.png",
    82: "@/assets/images/heavy-rain.png",
    85: "@/assets/images/light-snow.png",
    86: "@/assets/images/moderate-snow.png",
    95: "@/assets/images/thunderstorm.png",
    96: "@/assets/images/thunderstorm.png",
    99: "@/assets/images/thunderstorm.png"
}